# Generated by Django 3.1.2 on 2020-12-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(verbose_name='締め切り日時')),
                ('task', models.CharField(max_length=500, verbose_name='やること')),
            ],
            options={
                'db_table': 'scheduler',
            },
        ),
    ]
