# Generated by Django 3.1.4 on 2020-12-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='deadline',
            field=models.DateTimeField(max_length=50, verbose_name='締め切り日時'),
        ),
    ]
