# Generated by Django 3.1.2 on 2020-12-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20201211_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='deadline',
            field=models.DateTimeField(verbose_name='締め切り日時'),
        ),
    ]
