# Generated by Django 3.1.2 on 2021-01-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20201220_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
